### ISSUE TITLE
GoSub

### ISSUE THREAD

**Issue by fabiotheo** [brandonlehmann/typescript-agi#2]
I'm trying to call a GoSub extension. I can talk to another peer, but when I hungup the call I receive this error:

Error: Could not execute gosub

This is my code:

https://pastebin.com/ujFZigbw

**Comment by brandonlehmann** [comment]
Is your sub actually named `dialler` or should it be `dialer`?

**Comment by fabiotheo** [comment]
`
context default
{
        _. => {
		NoOp(${CALLERID(num)});
		AGI(agi://${IPCOM.FastAGI});
		hangup:
		Hangup();
        };
};

context dialler 
{
        _. => {
                NoOp(Ligando de ${CALLERID(num)} para Ramal ${RAMAL});
                Dial(PJSIP/${RAMAL},20,Tt);
                hangup:
                Hangup();
        
	}
}

`

**Comment by brandonlehmann** [comment]
I have to admit, I haven't seen dialplan syntax like that before but I don't run the latest & greatest copies of Asterisk everywhere.

What do your asterisk logs indicate?

**Comment by brandonlehmann** [comment]
Closing due to stale issue.
